version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    command: ["streamlit", "run", "app.py"]
